/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainImport } from './routes/main'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboardLayout/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as DashboardLayoutOrdersImport } from './routes/_dashboardLayout/orders'
import { Route as DashboardLayoutDashboardImport } from './routes/_dashboardLayout/dashboard'

// Create/Update Routes

const MainRoute = MainImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRoute,
} as any)

const DashboardLayoutRouteRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardLayoutOrdersRoute = DashboardLayoutOrdersImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardLayoutRouteRoute,
} as any)

const DashboardLayoutDashboardRoute = DashboardLayoutDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardLayoutRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/_dashboardLayout/dashboard': {
      id: '/_dashboardLayout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutDashboardImport
      parentRoute: typeof DashboardLayoutRouteImport
    }
    '/_dashboardLayout/orders': {
      id: '/_dashboardLayout/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof DashboardLayoutOrdersImport
      parentRoute: typeof DashboardLayoutRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface DashboardLayoutRouteRouteChildren {
  DashboardLayoutDashboardRoute: typeof DashboardLayoutDashboardRoute
  DashboardLayoutOrdersRoute: typeof DashboardLayoutOrdersRoute
}

const DashboardLayoutRouteRouteChildren: DashboardLayoutRouteRouteChildren = {
  DashboardLayoutDashboardRoute: DashboardLayoutDashboardRoute,
  DashboardLayoutOrdersRoute: DashboardLayoutOrdersRoute,
}

const DashboardLayoutRouteRouteWithChildren =
  DashboardLayoutRouteRoute._addFileChildren(DashboardLayoutRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof DashboardLayoutRouteRouteWithChildren
  '/main': typeof MainRoute
  '/dashboard': typeof DashboardLayoutDashboardRoute
  '/orders': typeof DashboardLayoutOrdersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof DashboardLayoutRouteRouteWithChildren
  '/main': typeof MainRoute
  '/dashboard': typeof DashboardLayoutDashboardRoute
  '/orders': typeof DashboardLayoutOrdersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_dashboardLayout': typeof DashboardLayoutRouteRouteWithChildren
  '/main': typeof MainRoute
  '/_dashboardLayout/dashboard': typeof DashboardLayoutDashboardRoute
  '/_dashboardLayout/orders': typeof DashboardLayoutOrdersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/main'
    | '/dashboard'
    | '/orders'
    | '/auth/login'
    | '/auth/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/main'
    | '/dashboard'
    | '/orders'
    | '/auth/login'
    | '/auth/signup'
  id:
    | '__root__'
    | '/'
    | '/_dashboardLayout'
    | '/main'
    | '/_dashboardLayout/dashboard'
    | '/_dashboardLayout/orders'
    | '/auth/login'
    | '/auth/signup'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRouteRoute: typeof DashboardLayoutRouteRouteWithChildren
  MainRoute: typeof MainRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRouteRoute: DashboardLayoutRouteRouteWithChildren,
  MainRoute: MainRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_dashboardLayout",
        "/main",
        "/auth/login",
        "/auth/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_dashboardLayout": {
      "filePath": "_dashboardLayout/route.tsx",
      "children": [
        "/_dashboardLayout/dashboard",
        "/_dashboardLayout/orders"
      ]
    },
    "/main": {
      "filePath": "main.tsx"
    },
    "/_dashboardLayout/dashboard": {
      "filePath": "_dashboardLayout/dashboard.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/orders": {
      "filePath": "_dashboardLayout/orders.tsx",
      "parent": "/_dashboardLayout"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
